[package]
name = "peter_prompt_macros"
version = "0.1.1"
edition = "2024"
license-file.workspace = true
homepage.workspace = true
repository.workspace = true
description = "Macros for peter prompt"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"
